from .register import register_user
from .register import login_user
from .customer import Customers
from .order import Orders
from .paymenttype import PaymentTypes
from .product import ProductData
from .producttype import ProductTypes
from .orderproduct import OrdersProducts
from .users import Users
